language: android

install: true

sudo: true

notifications:
  email: false

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # SDK version to compile project
    - android-28

script: ./gradlew test
